#!/usr/bin/env python3
"""Generate docs/configuration.md from terraform/variables.tf.

variables.tf is the only place a setting is defined, so it is the only place
worth documenting one. This reads it and writes the reference: every variable,
its type, its default, whether it is required, and -- the part that is hard to
find otherwise -- the set of values a validation block will actually accept.

Run it with `make docs`. tests/test_config_docs.py runs the same generation and
fails if the checked-in file differs, so the reference cannot drift away from
the variables it describes.

There is a general-purpose tool for this (terraform-docs). This exists instead
because it is thirty lines of parsing against one file we control, against a
binary every contributor would have to install, and because it can pull the
allowed-value sets out of the validation blocks, which terraform-docs does not.

Standard library only, so there is nothing to install.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
VARIABLES = os.path.join(REPO, "terraform", "variables.tf")
OUTPUT = os.path.join(REPO, "docs", "configuration.md")

# `# ----` / `# Compute` / `# ----`: the section banners in variables.tf.
BANNER = re.compile(r"^#\s*-{10,}\s*$")
SECTION = re.compile(r"^#\s+(.*\S)\s*$")
VARIABLE = re.compile(r'^variable\s+"([^"]+)"\s*\{')

# contains(["a", "b"], var.x) -- the enumerated values a validation accepts.
CONTAINS = re.compile(r"contains\(\s*\[([^\]]*)\]")
QUOTED = re.compile(r'"((?:[^"\\]|\\.)*)"')

PREAMBLE = """# Configuration reference

Every setting for the whole stack, generated from `terraform/variables.tf`.

**Do not edit this file.** `make docs` regenerates it and `make test` fails
when it is stale, so it always describes the variables as they actually are.

Settings go in `terraform/terraform.tfvars`, which is gitignored because the
Discord webhook URL in it is a credential. Copy `terraform.tfvars.example` to
start. Anything you leave out takes the default below.

```hcl
# terraform/terraform.tfvars
discord_public_key    = "..."          # required
accept_minecraft_eula = true           # required
idle_timeout_minutes  = 20             # anything else is optional
```

**Almost nothing here rebuilds the instance.** Terraform publishes these to one
SSM parameter which the instance re-reads on every boot, so `terraform apply`
followed by `/stop` and `/start` in Discord applies the change. The exceptions
are called out on the settings they apply to.

**[Applying changes](applying-changes.md) lists every exception in one place** —
which settings apply without a restart, which are only read while the server is
being created, and how to change one of those on a server that already exists.

Related, with more context than a reference entry can carry:

- [What it costs](../README.md#what-it-costs) — which settings are free-tier bound
- [Route 53 setup](route53-setup.md) — the `route53_*` and `addressing_mode` settings
- [Mods](mods.md) — `server_mods`, and tuning the server for more players
- [Applying changes](applying-changes.md) — what each setting needs before it takes effect
- [Operations](operations.md) — shells, backups, restores, upgrades
"""


def read_blocks(text):
    """Yield (section, name, body) for every variable block, in file order."""
    lines = text.splitlines()
    section = "General"
    index = 0

    while index < len(lines):
        line = lines[index]

        # A banner comment, its title, and its closing banner.
        if BANNER.match(line) and index + 2 < len(lines) and BANNER.match(lines[index + 2]):
            match = SECTION.match(lines[index + 1])
            if match:
                section = match.group(1)
                index += 3
                continue

        match = VARIABLE.match(line)
        if match:
            depth = line.count("{") - line.count("}")
            body = []
            index += 1
            while index < len(lines) and depth > 0:
                depth += lines[index].count("{") - lines[index].count("}")
                if depth > 0:
                    body.append(lines[index])
                index += 1
            yield section, match.group(1), "\n".join(body)
            continue

        index += 1


def field(body, name):
    """The single-line value of `name = ...`, or None."""
    match = re.search(rf"^\s*{name}\s*=\s*(.+?)\s*$", body, re.MULTILINE)
    return match.group(1) if match else None


def description(body):
    """The description, from either a heredoc or a quoted string."""
    heredoc = re.search(r"description\s*=\s*<<-?(\w+)\n(.*?)^\s*\1\s*$", body, re.DOTALL | re.MULTILINE)
    if heredoc:
        return dedent_heredoc(heredoc.group(2))

    quoted = field(body, "description")
    if quoted and quoted.startswith('"'):
        match = QUOTED.match(quoted)
        if match:
            return unescape(match.group(1))
    return ""


def dedent_heredoc(text):
    """Strip the common leading whitespace, as Terraform's <<- does."""
    lines = text.rstrip().split("\n")
    indents = [len(line) - len(line.lstrip()) for line in lines if line.strip()]
    margin = min(indents) if indents else 0
    return "\n".join(line[margin:] if line.strip() else "" for line in lines)


def unescape(text):
    return text.replace('\\"', '"').replace("\\\\", "\\").replace("\\n", "\n")


def allowed_values(body):
    """The values a `contains([...], var.x)` validation accepts."""
    match = CONTAINS.search(body)
    if not match:
        return []
    return [unescape(value) for value in QUOTED.findall(match.group(1))]


def constraint(body):
    """The validation's error_message, which states the rule in prose."""
    match = re.search(r"error_message\s*=\s*\"((?:[^\"\\]|\\.)*)\"", body, re.DOTALL)
    return unescape(match.group(1)).strip() if match else None


def parse(text):
    variables = []
    for section, name, body in read_blocks(text):
        default = field(body, "default")
        variables.append(
            {
                "section": section,
                "name": name,
                "type": field(body, "type") or "string",
                "default": default,
                "required": default is None,
                "sensitive": field(body, "sensitive") == "true",
                "description": description(body),
                "allowed": allowed_values(body),
                "constraint": constraint(body),
            }
        )
    return variables


def summarise(description_text):
    """First sentence, for the index table."""
    first = description_text.strip().split("\n\n")[0].replace("\n", " ").strip()
    match = re.match(r"^(.*?[.!?])(\s|$)", first)
    summary = match.group(1) if match else first
    # Long descriptions get their opening clause; the full text is a click away.
    if len(summary) > 110:
        summary = summary[:107].rsplit(" ", 1)[0] + "..."
    return summary.replace("|", "\\|")


def render(variables):
    out = [PREAMBLE]

    # Index, grouped the way variables.tf groups them.
    out.append("\n## Index\n")
    for section in dict.fromkeys(v["section"] for v in variables):
        out.append(f"\n**{section}**\n")
        out.append("| Setting | Type | Default | |")
        out.append("| ------- | ---- | ------- | - |")
        for variable in (v for v in variables if v["section"] == section):
            default = "**required**" if variable["required"] else f"`{variable['default']}`"
            out.append(
                f"| [`{variable['name']}`](#{variable['name']}) "
                f"| `{variable['type']}` | {default} | {summarise(variable['description'])} |"
            )
    out.append("")

    # Full entries.
    for section in dict.fromkeys(v["section"] for v in variables):
        out.append(f"\n## {section}\n")
        for variable in (v for v in variables if v["section"] == section):
            out.append(f"### `{variable['name']}`\n")

            facts = [f"`{variable['type']}`"]
            facts.append("**required**" if variable["required"] else f"default `{variable['default']}`")
            if variable["sensitive"]:
                facts.append("sensitive — kept out of Terraform output")
            out.append(" · ".join(facts) + "\n")

            # An enumerated validation gives the exact set; a regex one only
            # gives the rule, so the error message is the clearest statement of
            # it available.
            if variable["allowed"]:
                out.append("Accepted values: " + ", ".join(f"`{v}`" for v in variable["allowed"]) + "\n")
            elif variable["constraint"]:
                out.append(f"Constraint: {variable['constraint']}\n")

            if variable["description"]:
                out.append(variable["description"] + "\n")

    return "\n".join(out).rstrip() + "\n"


def generate():
    with open(VARIABLES, encoding="utf-8") as handle:
        return render(parse(handle.read()))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs/configuration.md is out of date, without writing it",
    )
    args = parser.parse_args()

    generated = generate()

    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            current = None
        if current != generated:
            sys.stderr.write(
                f"{os.path.relpath(OUTPUT, REPO)} is out of date. Run: make docs\n"
            )
            return 1
        return 0

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generated)
    print(f"wrote {os.path.relpath(OUTPUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
